/**
 * Grammalecte, flattened: every French word it knows, and the lemma it belongs to.
 *
 * The [Dictionnaire orthographique français](https://grammalecte.net/) by
 * Olivier R. (MPL 2.0, "classique" v7.5) is the dictionary Firefox and
 * LibreOffice spell with, and the `dictionary-fr` package ships it unchanged as
 * a Hunspell pair: a list of lemmas with affix flags, and the rules those flags
 * stand for. Expanding it gives around 2.9 million forms, of which 440,000 are
 * plain lower-case French.
 *
 * Two scripts need it and they need different halves. `build-lexicon.mjs` wants
 * the words; `build-definitions.mjs` wants the lemma each form belongs to, so a
 * conjugation with no Wiktionary entry of its own can still show what it is a
 * form of. Expanding once here keeps the flag rules in one place.
 *
 * See server/data/LICENCE-DEFINITIONS.md: MPL 2.0 is copyleft per file, which
 * is why the words end up in a file of their own.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import grammalecte from 'dictionary-fr';
import { IterableHunspellReader } from 'hunspell-reader';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const WORK = resolve(root, '.work');

/** Lower-case, unaccented or accented, and nothing else: no proper nouns, no dots. */
export const FRENCH_WORD = /^[a-zàâäçéèêëîïôöùûüÿœ]+$/;

/**
 * Hunspell flags whose forms are not words to play.
 *
 * `U.` is the SI unit prefix table: nineteen prefixes applied to every unit
 * symbol, which turns `sr` into `zsr`, `nsr`, `dsr` and `cal` into `dcal`,
 * `ncal`. Generated by rule rather than written by anybody, and they were the
 * only real noise the expansion produced. The rest are the elisions, whose
 * forms carry an apostrophe and cannot be traced on a grid.
 *
 * The file declares `FLAG long`, so every flag is exactly two characters.
 */
const UNPLAYABLE_FLAGS = new Set([
  'U.',
  'Ui',
  'Um',
  "c'",
  "d'",
  "D'",
  "j'",
  "l'",
  "L'",
  "m'",
  "n'",
  "q'",
  "Q'",
  'Qj',
  "s'",
  'Si',
  "t'",
]);

/**
 * Writes the trimmed dictionary beside the other reference sources.
 *
 * The reader takes file paths rather than strings, so the copy has to land
 * somewhere; `.work/` is where the Wiktionary extract and Lexique already live.
 */
function trimmedSource() {
  const utf8 = new TextDecoder();
  const lines = utf8.decode(grammalecte.dic).split('\n');

  const kept = [];
  for (let index = 1; index < lines.length; index++) {
    const line = lines[index];
    if (!line) continue;
    const slash = line.indexOf('/');
    if (slash < 0) {
      kept.push(line);
      continue;
    }
    const flags = line.slice(slash + 1);
    const playable = [];
    for (let at = 0; at + 1 < flags.length; at += 2) {
      const flag = flags.slice(at, at + 2);
      if (!UNPLAYABLE_FLAGS.has(flag)) playable.push(flag);
    }
    const word = line.slice(0, slash);
    kept.push(playable.length > 0 ? `${word}/${playable.join('')}` : word);
  }

  mkdirSync(WORK, { recursive: true });
  const dic = resolve(WORK, 'grammalecte-fr.dic');
  const aff = resolve(WORK, 'grammalecte-fr.aff');
  writeFileSync(dic, `${kept.length}\n${kept.join('\n')}\n`, 'utf8');
  writeFileSync(aff, utf8.decode(grammalecte.aff), 'utf8');
  return { dic, aff, entries: kept.length };
}

/**
 * Every plain French form Grammalecte knows, mapped to its lemma.
 *
 * A form that is its own lemma maps to itself, which is how a caller tells a
 * headword from an inflection. Where two lemmas produce the same form, the
 * first wins; the alternative is a list per form, and no caller wants one.
 */
export async function grammalecteLemmas() {
  const source = trimmedSource();
  const reader = await IterableHunspellReader.createFromFiles(source.aff, source.dic);
  const lemmas = new Map();
  let expanded = 0;
  for (const affWord of reader.seqAffWords()) {
    expanded++;
    const form = affWord.word;
    if (!FRENCH_WORD.test(form) || lemmas.has(form)) continue;
    const slash = affWord.dic.indexOf('/');
    lemmas.set(form, slash < 0 ? affWord.dic : affWord.dic.slice(0, slash));
  }
  return { lemmas, expanded, entries: source.entries };
}
